.TH "__PACKPATS" "8" "2007 Jun 7" "Debian Project" ""
.SH "NAME"
\fB__packpats\fB \- Auxiliary script used by \fBxafrestore\fB
.SH "DESCRIPTION"
The functionality of this program is not important to any user or administrator. 
It is main intention is to speed up the index scanning, cause otherwise the
Tcl/Tk\-Script must do the entire evaluation, what is a real CPU hog.

.br 
\fBThis program is part of afbackup\-client\fB
.SH "SEE ALSO"
\fBafclient(8)\fB, \fBxafclientconfig(8)\fB, \fBfull_backup(8)\fB, \fBincr_backup(8)\fB, \fBafverify(8)\fB, \fBafrestore(8)\fB, \fBxafrestore(8)\fB, \fBafserver(8)\fB, \fBafmserver(8)\fB, \fBcopy_tape(8)\fB, \fBafclient.conf(8)\fB,
\fBupdate_indexes(8)\fB
.SH "AUTHOR"
.PP 
This manual page was written by Rene Mayorga <rmayorga@debian.org.sv> for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common\-licenses/GPL. 
