#!/bin/sh
################### Start of $RCSfile: __mt,v $ ##################
#
# $Source: /home/alb/afbackup/afbackup-3.5.8.12/RCS/__mt,v $
# $Id: __mt,v 1.2 2004/07/08 20:34:42 alb Exp alb $
# $Date: 2004/07/08 20:34:42 $
# $Author: alb $
#
#
####### description ################################################
#
#
#
####################################################################

n=$#
if [ $n -ge 2 ] ; then
  m=`expr $n - 1`
  eval cmd='$'$m
  eval num='$'$n
  if [ '(' "$cmd" = "bsf" -o "$cmd" = "fsf" -o "$cmd" = "fsr" -o "$cmd" = "bsr" ')' -a $num -eq 0 ] ; then
    exit 0
  fi
fi

exec mt "$@"
