#!/bin/sh
#
# $Source: /home/alb/afbackup/afbackup-3.5.8.12/RCS/rcsupdateall,v $
# $Id: rcsupdateall,v 1.2 2004/07/08 20:36:11 alb Exp alb $
#

PWD=`pwd`
SYMNAME=`basename $PWD | sed 's/^[^-]*-/v/g' | tr . - | sed 's/beta/b/g;s/alpha/a/g'`

echo "OK to check in all files with the symbolic tag $SYMNAME (yes/no) ?"
read a
echo "$a" | egrep -i '^ye?s?$' >/dev/null
if [ $? -ne 0 ] ; then
  echo "You disagree. Ok, then patch me. Exiting." >&2
  exit 1
fi

for f in `find . -type f -print` ; do
  ci -l -N"$SYMNAME" -m"automatically checked in by `basename $0`." $f </dev/null
done
